version: '3.8'
services:
  app:
    container_name: app
    image: app:latest
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8000:8000"
    environment:
      - DB_URI=$DB_URI
      - NODE_ENV=production
      - PORT=$PORT